name: CI/CD with Docker

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build & Docker Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Set Run Permission to gradlew
        run: chmod +x gradlew

      - name: Build With Gradle
        run: ./gradlew clean build

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_ID }}
          tags: |
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Git Config
        run: |
          git config --global user.email "g"
          git config --global user.name "GitHub Action"

      - name: Checkout K8s Resource Repository
        uses: actions/checkout@master
        with:
          repository: Aftermoon-dev/k8s-argocd
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          
      - name: Update Application Container
        run: sed -i "s|${{ steps.meta.outputs.labels }}:[^ ]*|${{ steps.meta.outputs.labels }}:${{ steps.meta.outputs.tags }}|" spring-boot-test-app/api-deployment.yaml

      - name: Git Push
        run: |
          git add spring-boot-test-app/api-deployment.yaml
          git commit -m "feat: Image ${{ steps.meta.outputs.tags }}"
          git push
          
