name: CI/CD with Docker

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build & Docker Push
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Set Run Permission to gradlew
        run: chmod +x gradlew

      - name: Build With Gradle
        run: ./gradlew clean build

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_ID }}
          tags: |
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
  update:
    name: Update GitOps Repository
    needs: build
    runs-on: ubuntu-latest
    env:
      tag: ${{ needs.build.outputs.tag }}
    steps:
        - name: Git Config
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Action"
  
        - name: Checkout K8s Resource Repository
          uses: actions/checkout@master
          with:
            repository: Aftermoon-dev/k8s-argocd
            token: ${{ secrets.GIT_ACCESS_TOKEN }}
            
        - name: Update Application Container
          run: sed -i "s|${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_ID }}:[^ ]*|${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_ID }}:${{ env.tag }}|" spring-boot-test-app/api-deployment.yml
  
        - name: Git Push
          run: |
            git add spring-boot-test-app/api-deployment.yml
            git commit -m "feat: Image ${{ steps.meta.outputs.tags }}"
            git push origin main
